#include "FactoryPresets.h"

#include "parameters/ParameterIDs.h"

namespace coolsynth::presets
{
    namespace
    {
        namespace ids = coolsynth::parameters::ids;

        // Each preset specifies all 67 parameters explicitly, so loading a preset
        // fully overrides the previous patch with no leftover knob state.

        constexpr PresetParameterValue kInitDefault[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.80f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 4.0f },
            { ids::oscBLevel, 0.68f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 3200.0f }, { ids::filterResonance, 0.08f },
            { ids::filterEnvAmount, 0.35f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 10.0f }, { ids::filterDecayMs, 220.0f },
            { ids::filterSustain, 0.12f }, { ids::filterReleaseMs, 220.0f },
            { ids::ampAttackMs, 5.0f }, { ids::ampDecayMs, 260.0f },
            { ids::ampSustain, 0.72f }, { ids::ampReleaseMs, 240.0f },
            { ids::lfoRateHz, 5.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.0f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 1.0f }, { ids::velocityToFilter, 0.0f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 0.0f }, { ids::driveAmount, 0.0f }, { ids::driveMix, 1.0f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 0.0f }, { ids::delayTimeMs, 250.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.0f },
            { ids::reverbEnabled, 0.0f }, { ids::reverbSize, 0.4f },
            { ids::reverbDamping, 0.5f }, { ids::reverbMix, 0.2f },
            { ids::masterGainDb, -12.0f },
        };

        constexpr PresetParameterValue kMonoSawLead[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, -5.0f },
            { ids::oscALevel, 0.85f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 7.0f },
            { ids::oscBLevel, 0.72f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 1800.0f }, { ids::filterResonance, 0.15f },
            { ids::filterEnvAmount, 0.5f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 5.0f }, { ids::filterDecayMs, 300.0f },
            { ids::filterSustain, 0.40f }, { ids::filterReleaseMs, 250.0f },
            { ids::ampAttackMs, 3.0f }, { ids::ampDecayMs, 300.0f },
            { ids::ampSustain, 0.85f }, { ids::ampReleaseMs, 180.0f },
            { ids::lfoRateHz, 5.5f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.05f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.08f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 35.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.15f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.5f }, { ids::velocityToFilter, 0.35f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.25f }, { ids::driveMix, 0.85f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 280.0f },
            { ids::delayFeedback, 0.3f }, { ids::delayMix, 0.18f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.35f },
            { ids::reverbDamping, 0.55f }, { ids::reverbMix, 0.15f },
            { ids::masterGainDb, -10.0f },
        };

        constexpr PresetParameterValue kHardSyncLead[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 3.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.95f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 1.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 0.0f },
            { ids::oscBLevel, 0.0f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 2200.0f }, { ids::filterResonance, 0.18f },
            { ids::filterEnvAmount, 0.6f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 10.0f }, { ids::filterDecayMs, 400.0f },
            { ids::filterSustain, 0.5f }, { ids::filterReleaseMs, 300.0f },
            { ids::ampAttackMs, 4.0f }, { ids::ampDecayMs, 250.0f },
            { ids::ampSustain, 0.9f }, { ids::ampReleaseMs, 250.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.5f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 25.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.1f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.6f }, { ids::velocityToFilter, 0.2f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.20f }, { ids::driveMix, 0.7f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.5f },
            { ids::chorusDepth, 0.3f }, { ids::chorusMix, 0.15f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 320.0f },
            { ids::delayFeedback, 0.3f }, { ids::delayMix, 0.15f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.35f },
            { ids::reverbDamping, 0.55f }, { ids::reverbMix, 0.18f },
            { ids::masterGainDb, -10.0f },
        };

        constexpr PresetParameterValue kSuperStack[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, -12.0f },
            { ids::oscALevel, 0.70f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 11.0f },
            { ids::oscBLevel, 0.70f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 2400.0f }, { ids::filterResonance, 0.10f },
            { ids::filterEnvAmount, 0.25f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 20.0f }, { ids::filterDecayMs, 600.0f },
            { ids::filterSustain, 0.4f }, { ids::filterReleaseMs, 500.0f },
            { ids::ampAttackMs, 30.0f }, { ids::ampDecayMs, 400.0f },
            { ids::ampSustain, 0.85f }, { ids::ampReleaseMs, 600.0f },
            { ids::lfoRateHz, 3.5f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.10f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 2.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.35f },
            { ids::panSpread, 0.7f }, { ids::velocityToAmp, 0.7f }, { ids::velocityToFilter, 0.2f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.15f }, { ids::driveMix, 0.6f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.45f },
            { ids::chorusDepth, 0.55f }, { ids::chorusMix, 0.4f },
            { ids::delayEnabled, 0.0f }, { ids::delayTimeMs, 250.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.0f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.45f },
            { ids::reverbDamping, 0.5f }, { ids::reverbMix, 0.25f },
            { ids::masterGainDb, -13.0f },
        };

        constexpr PresetParameterValue kFatMonoBass[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 1.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.85f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 1.0f }, { ids::oscBFineCents, -5.0f },
            { ids::oscBLevel, 0.70f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 600.0f }, { ids::filterResonance, 0.25f },
            { ids::filterEnvAmount, 0.55f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 4.0f }, { ids::filterDecayMs, 180.0f },
            { ids::filterSustain, 0.0f }, { ids::filterReleaseMs, 180.0f },
            { ids::ampAttackMs, 3.0f }, { ids::ampDecayMs, 220.0f },
            { ids::ampSustain, 0.7f }, { ids::ampReleaseMs, 120.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 12.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.10f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.85f }, { ids::velocityToFilter, 0.4f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.35f }, { ids::driveMix, 0.9f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 0.0f }, { ids::delayTimeMs, 250.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.0f },
            { ids::reverbEnabled, 0.0f }, { ids::reverbSize, 0.4f },
            { ids::reverbDamping, 0.5f }, { ids::reverbMix, 0.0f },
            { ids::masterGainDb, -9.0f },
        };

        constexpr PresetParameterValue kPureSub[] = {
            { ids::oscAWave, 3.0f }, { ids::oscAOctave, 1.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.9f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 1.0f }, { ids::oscBOctave, 0.0f }, { ids::oscBFineCents, 0.0f },
            { ids::oscBLevel, 0.45f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 400.0f }, { ids::filterResonance, 0.05f },
            { ids::filterEnvAmount, 0.1f }, { ids::filterKeyTracking, 2.0f },
            { ids::filterAttackMs, 5.0f }, { ids::filterDecayMs, 200.0f },
            { ids::filterSustain, 0.3f }, { ids::filterReleaseMs, 200.0f },
            { ids::ampAttackMs, 5.0f }, { ids::ampDecayMs, 200.0f },
            { ids::ampSustain, 0.95f }, { ids::ampReleaseMs, 200.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 10.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.0f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.85f }, { ids::velocityToFilter, 0.1f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 0.0f }, { ids::driveAmount, 0.0f }, { ids::driveMix, 1.0f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 0.0f }, { ids::delayTimeMs, 250.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.0f },
            { ids::reverbEnabled, 0.0f }, { ids::reverbSize, 0.4f },
            { ids::reverbDamping, 0.5f }, { ids::reverbMix, 0.0f },
            { ids::masterGainDb, -8.0f },
        };

        constexpr PresetParameterValue kAcidBass[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.9f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 1.0f }, { ids::oscBFineCents, 0.0f },
            { ids::oscBLevel, 0.30f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 350.0f }, { ids::filterResonance, 0.75f },
            { ids::filterEnvAmount, 0.85f }, { ids::filterKeyTracking, 2.0f },
            { ids::filterAttackMs, 2.0f }, { ids::filterDecayMs, 180.0f },
            { ids::filterSustain, 0.0f }, { ids::filterReleaseMs, 120.0f },
            { ids::ampAttackMs, 2.0f }, { ids::ampDecayMs, 120.0f },
            { ids::ampSustain, 0.0f }, { ids::ampReleaseMs, 100.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 2.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 80.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.08f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.5f }, { ids::velocityToFilter, 0.6f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.30f }, { ids::driveMix, 0.8f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 180.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.10f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.30f },
            { ids::reverbDamping, 0.6f }, { ids::reverbMix, 0.10f },
            { ids::masterGainDb, -10.0f },
        };

        constexpr PresetParameterValue kGlassyPluck[] = {
            { ids::oscAWave, 1.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.80f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 3.0f }, { ids::oscBFineCents, 3.0f },
            { ids::oscBLevel, 0.40f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 2800.0f }, { ids::filterResonance, 0.20f },
            { ids::filterEnvAmount, 0.65f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 1.0f }, { ids::filterDecayMs, 180.0f },
            { ids::filterSustain, 0.0f }, { ids::filterReleaseMs, 200.0f },
            { ids::ampAttackMs, 1.0f }, { ids::ampDecayMs, 160.0f },
            { ids::ampSustain, 0.0f }, { ids::ampReleaseMs, 280.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.12f },
            { ids::panSpread, 0.25f }, { ids::velocityToAmp, 0.7f }, { ids::velocityToFilter, 0.4f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 0.0f }, { ids::driveAmount, 0.0f }, { ids::driveMix, 1.0f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.55f },
            { ids::chorusDepth, 0.35f }, { ids::chorusMix, 0.18f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 320.0f },
            { ids::delayFeedback, 0.35f }, { ids::delayMix, 0.22f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.55f },
            { ids::reverbDamping, 0.4f }, { ids::reverbMix, 0.30f },
            { ids::masterGainDb, -11.0f },
        };

        constexpr PresetParameterValue kFunkyClav[] = {
            { ids::oscAWave, 0.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.85f }, { ids::oscAPulseWidth, 0.22f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 0.0f }, { ids::oscBOctave, 3.0f }, { ids::oscBFineCents, 3.0f },
            { ids::oscBLevel, 0.45f }, { ids::oscBPulseWidth, 0.78f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 2200.0f }, { ids::filterResonance, 0.30f },
            { ids::filterEnvAmount, 0.55f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 1.0f }, { ids::filterDecayMs, 120.0f },
            { ids::filterSustain, 0.0f }, { ids::filterReleaseMs, 120.0f },
            { ids::ampAttackMs, 1.0f }, { ids::ampDecayMs, 180.0f },
            { ids::ampSustain, 0.0f }, { ids::ampReleaseMs, 180.0f },
            { ids::lfoRateHz, 4.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.0f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.18f },
            { ids::panSpread, 0.20f }, { ids::velocityToAmp, 0.85f }, { ids::velocityToFilter, 0.5f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.20f }, { ids::driveMix, 0.7f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.50f },
            { ids::chorusDepth, 0.30f }, { ids::chorusMix, 0.18f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 180.0f },
            { ids::delayFeedback, 0.20f }, { ids::delayMix, 0.15f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.30f },
            { ids::reverbDamping, 0.55f }, { ids::reverbMix, 0.12f },
            { ids::masterGainDb, -10.0f },
        };

        constexpr PresetParameterValue kBrassStack[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, -3.0f },
            { ids::oscALevel, 0.78f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 0.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 3.0f },
            { ids::oscBLevel, 0.65f }, { ids::oscBPulseWidth, 0.35f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.05f },
            { ids::filterCutoffHz, 1400.0f }, { ids::filterResonance, 0.18f },
            { ids::filterEnvAmount, 0.70f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 8.0f }, { ids::filterDecayMs, 220.0f },
            { ids::filterSustain, 0.30f }, { ids::filterReleaseMs, 220.0f },
            { ids::ampAttackMs, 12.0f }, { ids::ampDecayMs, 200.0f },
            { ids::ampSustain, 0.85f }, { ids::ampReleaseMs, 250.0f },
            { ids::lfoRateHz, 4.5f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.05f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.18f },
            { ids::panSpread, 0.15f }, { ids::velocityToAmp, 0.8f }, { ids::velocityToFilter, 0.4f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.18f }, { ids::driveMix, 0.7f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.55f },
            { ids::chorusDepth, 0.30f }, { ids::chorusMix, 0.18f },
            { ids::delayEnabled, 0.0f }, { ids::delayTimeMs, 250.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.0f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.40f },
            { ids::reverbDamping, 0.50f }, { ids::reverbMix, 0.20f },
            { ids::masterGainDb, -11.0f },
        };

        constexpr PresetParameterValue kWarmAnalogPad[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, -7.0f },
            { ids::oscALevel, 0.70f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 2.0f }, { ids::oscBOctave, 2.0f }, { ids::oscBFineCents, 8.0f },
            { ids::oscBLevel, 0.70f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 1600.0f }, { ids::filterResonance, 0.05f },
            { ids::filterEnvAmount, 0.20f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 600.0f }, { ids::filterDecayMs, 1200.0f },
            { ids::filterSustain, 0.5f }, { ids::filterReleaseMs, 1500.0f },
            { ids::ampAttackMs, 800.0f }, { ids::ampDecayMs, 1500.0f },
            { ids::ampSustain, 0.85f }, { ids::ampReleaseMs, 2000.0f },
            { ids::lfoRateHz, 0.6f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.10f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.25f },
            { ids::panSpread, 0.50f }, { ids::velocityToAmp, 0.50f }, { ids::velocityToFilter, 0.10f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.10f }, { ids::driveMix, 0.5f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.40f },
            { ids::chorusDepth, 0.55f }, { ids::chorusMix, 0.45f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 420.0f },
            { ids::delayFeedback, 0.30f }, { ids::delayMix, 0.15f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.60f },
            { ids::reverbDamping, 0.40f }, { ids::reverbMix, 0.35f },
            { ids::masterGainDb, -13.0f },
        };

        constexpr PresetParameterValue kEtherealDream[] = {
            { ids::oscAWave, 3.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.70f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 1.0f }, { ids::oscBOctave, 3.0f }, { ids::oscBFineCents, 7.0f },
            { ids::oscBLevel, 0.55f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.04f },
            { ids::filterCutoffHz, 2400.0f }, { ids::filterResonance, 0.05f },
            { ids::filterEnvAmount, 0.15f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 1000.0f }, { ids::filterDecayMs, 2000.0f },
            { ids::filterSustain, 0.6f }, { ids::filterReleaseMs, 2500.0f },
            { ids::ampAttackMs, 1400.0f }, { ids::ampDecayMs, 2500.0f },
            { ids::ampSustain, 0.85f }, { ids::ampReleaseMs, 3500.0f },
            { ids::lfoRateHz, 0.3f }, { ids::lfoWave, 3.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.12f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.20f },
            { ids::panSpread, 0.60f }, { ids::velocityToAmp, 0.40f }, { ids::velocityToFilter, 0.05f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 0.0f }, { ids::driveAmount, 0.0f }, { ids::driveMix, 1.0f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.35f },
            { ids::chorusDepth, 0.55f }, { ids::chorusMix, 0.45f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 480.0f },
            { ids::delayFeedback, 0.45f }, { ids::delayMix, 0.25f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.80f },
            { ids::reverbDamping, 0.35f }, { ids::reverbMix, 0.55f },
            { ids::masterGainDb, -13.0f },
        };

        constexpr PresetParameterValue kWobbleBass[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 1.0f }, { ids::oscAFineCents, 0.0f },
            { ids::oscALevel, 0.90f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 0.0f }, { ids::oscBOctave, 1.0f }, { ids::oscBFineCents, -5.0f },
            { ids::oscBLevel, 0.60f }, { ids::oscBPulseWidth, 0.35f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 300.0f }, { ids::filterResonance, 0.50f },
            { ids::filterEnvAmount, 0.35f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 2.0f }, { ids::filterDecayMs, 220.0f },
            { ids::filterSustain, 0.3f }, { ids::filterReleaseMs, 180.0f },
            { ids::ampAttackMs, 2.0f }, { ids::ampDecayMs, 220.0f },
            { ids::ampSustain, 0.9f }, { ids::ampReleaseMs, 180.0f },
            { ids::lfoRateHz, 2.5f }, { ids::lfoWave, 2.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.55f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 15.0f }, { ids::playMode, 1.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.10f },
            { ids::panSpread, 0.0f }, { ids::velocityToAmp, 0.85f }, { ids::velocityToFilter, 0.30f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.30f }, { ids::driveMix, 0.85f },
            { ids::chorusEnabled, 0.0f }, { ids::chorusRateHz, 0.6f },
            { ids::chorusDepth, 0.4f }, { ids::chorusMix, 0.3f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 240.0f },
            { ids::delayFeedback, 0.25f }, { ids::delayMix, 0.12f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.35f },
            { ids::reverbDamping, 0.55f }, { ids::reverbMix, 0.10f },
            { ids::masterGainDb, -9.0f },
        };

        constexpr PresetParameterValue kSciFiTexture[] = {
            { ids::oscAWave, 0.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, 20.0f },
            { ids::oscALevel, 0.80f }, { ids::oscAPulseWidth, 0.28f }, { ids::oscASyncEnabled, 1.0f },
            { ids::oscBWave, 1.0f }, { ids::oscBOctave, 1.0f }, { ids::oscBFineCents, -15.0f },
            { ids::oscBLevel, 0.55f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 1.0f },
            { ids::noiseLevel, 0.18f },
            { ids::filterCutoffHz, 1500.0f }, { ids::filterResonance, 0.45f },
            { ids::filterEnvAmount, 0.50f }, { ids::filterKeyTracking, 0.0f },
            { ids::filterAttackMs, 3.0f }, { ids::filterDecayMs, 600.0f },
            { ids::filterSustain, 0.4f }, { ids::filterReleaseMs, 800.0f },
            { ids::ampAttackMs, 8.0f }, { ids::ampDecayMs, 600.0f },
            { ids::ampSustain, 0.7f }, { ids::ampReleaseMs, 1200.0f },
            { ids::lfoRateHz, 0.8f }, { ids::lfoWave, 0.0f },
            { ids::lfoToOscPitch, 0.10f }, { ids::lfoToPulseWidth, 0.30f },
            { ids::lfoToFilterCutoff, 0.25f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.45f }, { ids::polyModEnvToOscPitch, 0.30f },
            { ids::polyModOscBToPulseWidth, 0.40f }, { ids::polyModEnvToPulseWidth, 0.20f },
            { ids::polyModOscBToFilterCutoff, 0.30f }, { ids::polyModEnvToFilterCutoff, 0.25f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.30f },
            { ids::panSpread, 0.50f }, { ids::velocityToAmp, 0.40f }, { ids::velocityToFilter, 0.30f },
            { ids::arpEnabled, 0.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 0.0f }, { ids::arpOctaveRange, 1.0f },
            { ids::arpGate, 0.5f }, { ids::arpLatch, 0.0f },
            { ids::driveEnabled, 1.0f }, { ids::driveAmount, 0.25f }, { ids::driveMix, 0.7f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.45f },
            { ids::chorusDepth, 0.50f }, { ids::chorusMix, 0.35f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 380.0f },
            { ids::delayFeedback, 0.55f }, { ids::delayMix, 0.30f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.70f },
            { ids::reverbDamping, 0.45f }, { ids::reverbMix, 0.45f },
            { ids::masterGainDb, -14.0f },
        };

        constexpr PresetParameterValue kArpBliss[] = {
            { ids::oscAWave, 2.0f }, { ids::oscAOctave, 2.0f }, { ids::oscAFineCents, -4.0f },
            { ids::oscALevel, 0.78f }, { ids::oscAPulseWidth, 0.5f }, { ids::oscASyncEnabled, 0.0f },
            { ids::oscBWave, 1.0f }, { ids::oscBOctave, 3.0f }, { ids::oscBFineCents, 5.0f },
            { ids::oscBLevel, 0.55f }, { ids::oscBPulseWidth, 0.5f }, { ids::oscBLowFrequencyMode, 0.0f },
            { ids::noiseLevel, 0.0f },
            { ids::filterCutoffHz, 2400.0f }, { ids::filterResonance, 0.18f },
            { ids::filterEnvAmount, 0.55f }, { ids::filterKeyTracking, 1.0f },
            { ids::filterAttackMs, 1.0f }, { ids::filterDecayMs, 180.0f },
            { ids::filterSustain, 0.0f }, { ids::filterReleaseMs, 200.0f },
            { ids::ampAttackMs, 1.0f }, { ids::ampDecayMs, 220.0f },
            { ids::ampSustain, 0.0f }, { ids::ampReleaseMs, 280.0f },
            { ids::lfoRateHz, 2.0f }, { ids::lfoWave, 1.0f },
            { ids::lfoToOscPitch, 0.0f }, { ids::lfoToPulseWidth, 0.0f },
            { ids::lfoToFilterCutoff, 0.08f }, { ids::modWheelToLfoDepth, 1.0f },
            { ids::polyModOscBToOscPitch, 0.0f }, { ids::polyModEnvToOscPitch, 0.0f },
            { ids::polyModOscBToPulseWidth, 0.0f }, { ids::polyModEnvToPulseWidth, 0.0f },
            { ids::polyModOscBToFilterCutoff, 0.0f }, { ids::polyModEnvToFilterCutoff, 0.0f },
            { ids::glideTimeMs, 0.0f }, { ids::playMode, 0.0f }, { ids::keyPriority, 0.0f },
            { ids::pitchBendRangeSemitones, 2.0f }, { ids::vintageAmount, 0.15f },
            { ids::panSpread, 0.35f }, { ids::velocityToAmp, 0.65f }, { ids::velocityToFilter, 0.30f },
            { ids::arpEnabled, 1.0f }, { ids::arpInternalTempoBpm, 120.0f },
            { ids::arpRateDivision, 3.0f }, { ids::arpPattern, 2.0f }, { ids::arpOctaveRange, 2.0f },
            { ids::arpGate, 0.45f }, { ids::arpLatch, 1.0f },
            { ids::driveEnabled, 0.0f }, { ids::driveAmount, 0.0f }, { ids::driveMix, 1.0f },
            { ids::chorusEnabled, 1.0f }, { ids::chorusRateHz, 0.50f },
            { ids::chorusDepth, 0.35f }, { ids::chorusMix, 0.20f },
            { ids::delayEnabled, 1.0f }, { ids::delayTimeMs, 375.0f },
            { ids::delayFeedback, 0.45f }, { ids::delayMix, 0.25f },
            { ids::reverbEnabled, 1.0f }, { ids::reverbSize, 0.55f },
            { ids::reverbDamping, 0.45f }, { ids::reverbMix, 0.30f },
            { ids::masterGainDb, -12.0f },
        };

        template <int N>
        constexpr FactoryPreset makeFactoryPreset(const char* name,
                                                  const char* category,
                                                  const PresetParameterValue (&values)[N]) noexcept
        {
            return { name, category, values, N };
        }

        const FactoryPreset kPresets[] = {
            makeFactoryPreset("Init Default",    "Init",  kInitDefault),
            makeFactoryPreset("Mono Saw Lead",   "Lead",  kMonoSawLead),
            makeFactoryPreset("Hard Sync Lead",  "Lead",  kHardSyncLead),
            makeFactoryPreset("Super Stack",     "Lead",  kSuperStack),
            makeFactoryPreset("Fat Mono Bass",   "Bass",  kFatMonoBass),
            makeFactoryPreset("Pure Sub",        "Bass",  kPureSub),
            makeFactoryPreset("Acid Bass",       "Bass",  kAcidBass),
            makeFactoryPreset("Glassy Pluck",    "Pluck", kGlassyPluck),
            makeFactoryPreset("Funky Clav",      "Keys",  kFunkyClav),
            makeFactoryPreset("Brass Stack",     "Keys",  kBrassStack),
            makeFactoryPreset("Warm Analog Pad", "Pad",   kWarmAnalogPad),
            makeFactoryPreset("Ethereal Dream",  "Pad",   kEtherealDream),
            makeFactoryPreset("Wobble Bass",     "Bass",  kWobbleBass),
            makeFactoryPreset("Sci-Fi Texture",  "FX",    kSciFiTexture),
            makeFactoryPreset("Arp Bliss",       "Arp",   kArpBliss),
        };

        constexpr int kPresetCount = static_cast<int>(sizeof(kPresets) / sizeof(kPresets[0]));
    }

    int getFactoryPresetCount() noexcept
    {
        return kPresetCount;
    }

    const FactoryPreset& getFactoryPreset(int index) noexcept
    {
        jassert(index >= 0 && index < kPresetCount);
        return kPresets[index];
    }

    void applyFactoryPreset(juce::AudioProcessorValueTreeState& apvts,
                            const FactoryPreset& preset)
    {
        for (int i = 0; i < preset.valueCount; ++i)
        {
            const auto& entry = preset.values[i];

            if (auto* parameter = apvts.getParameter(entry.parameterId))
            {
                const auto normalised = parameter->getNormalisableRange().convertTo0to1(entry.value);
                parameter->beginChangeGesture();
                parameter->setValueNotifyingHost(juce::jlimit(0.0f, 1.0f, normalised));
                parameter->endChangeGesture();
            }
        }
    }
}
